### ISSUE TITLE
Blocking usb device

### ISSUE THREAD

**Issue by leochou0729** [zhuowei/MacUptimeChanger#1]
Hello, 
  Thanks for your great article. I'm a new MacOS developer. I need to create a client app, which can block mass storage devices. After googling, I found little information how to do that. The only way I found is to install Configuration Profiles to prevent external volumes mounting. I'm wondering if I can develop a kernel extension and use similar technique to accomplish that. It is better I can block specific devices based on their pid/vid or something instead of all usb devices. Do you have any suggestions? Thanks!

**Comment by zhuowei** [comment]
@leochou0729 I'm probably not the best person to ask for this, as this is literally the only kext I've ever made in my life: you should maybe ask some IOKit experts on how best to do this, or look at how Apple's own provisioning does it.

Sorry about this!
